In [17]:
suppressPackageStartupMessages({
    require(circlize)
    library(dplyr)
})

In [28]:
mat  <- read.delim("Brain_chordates_high_res/Brain_chordates_Refined_family.MappingTables.links.csv", header = T, sep = ",")

In [29]:
mat$groups1 <- vapply(mat$source, FUN = function(x){strsplit(x, split = '_')[[1]][2]}, FUN.VALUE = character(1))
mat$groups2 <- vapply(mat$target, FUN = function(x){strsplit(x, split = '_')[[1]][2]}, FUN.VALUE = character(1))

In [30]:
mat[mat$source == 'hs_Diencephalon GABAergic neurons', ]

   source                            target
12 hs_Diencephalon GABAergic neurons mm_Mesencephalon GABAergic neurons
13 hs_Diencephalon GABAergic neurons mm_Mesencephalon cholinergic neurons
14 hs_Diencephalon GABAergic neurons mm_Mesencephalon glutamatergic neurons
15 hs_Diencephalon GABAergic neurons mm_Peptidergic neurons
16 hs_Diencephalon GABAergic neurons mm_Rhombencephalon cholinergic neurons
17 hs_Diencephalon GABAergic neurons pv_Mesencephalon GABAergic neurons
18 hs_Diencephalon GABAergic neurons pm_Diencephalon GABAergic neurons
19 hs_Diencephalon GABAergic neurons pm_Dopaminergic neurons
20 hs_Diencephalon GABAergic neurons pm_Mesencephalon GABAergic neurons
21 hs_Diencephalon GABAergic neurons pm_Peptidergic neurons
22 hs_Diencephalon GABAergic neurons bf_0
23 hs_Diencephalon GABAergic neurons bf_1
24 hs_Diencephalon GABAergic neurons bf_10
25 hs_Diencephalon GABAergic neurons bf_16
26 hs_Diencephalon GABAergic neurons bf_9
   value     groups1                        groups2
12 0.6337466 Diencephalon GABAergic neurons Mesencephalon GABAergic neurons
13 0.1801335 Diencephalon GABAergic neurons Mesencephalon cholinergic neurons
14 0.1056547 Diencephalon GABAergic neurons Mesencephalon glutamatergic neurons
15 0.3463462 Diencephalon GABAergic neurons Peptidergic neurons
16 0.1310203 Diencephalon GABAergic neurons Rhombencephalon cholinergic neurons
17 0.6105214 Diencephalon GABAergic neurons Mesencephalon GABAergic neurons
18 0.2558659 Diencephalon GABAergic neurons Diencephalon GABAergic neurons
19 0.1071346 Diencephalon GABAergic neurons Dopaminergic neurons
20 0.6174078 Diencephalon GABAergic neurons Mesencephalon GABAergic neurons
21 0.1716792 Diencephalon GABAergic neurons Peptidergic neurons
22 0.1386237 Diencephalon GABAergic neurons 0
23 0.3412878 Diencephalon GABAergic neurons 1
24 0.1218103 Diencephalon GABAergic neurons 10
25 0.2266332 Diencephalon GABAergic neurons 16
26 0.1213440 Diencephalon GABAergic neurons 9

In [31]:
# keep only neuronal major groups
n <- c('Diencephalon glutamatergic neurons', 'Diencephalon GABAergic neurons','Mesencephalon glutamatergic neurons',
      'Mesencephalon GABAergic neurons','Rhombencephalon glutamatergic neurons','Rhombencephalon GABAergic neurons',
      'Splatter', 'Telencephalon glutamatergic neurons', 'Telencephalon GABAergic neurons',
       18,11,10,13,7,15,0,1,14,21,2,17,16,9)

mat <- mat %>% filter(groups1 %in% n & groups2 %in% n)
mat <- mat %>% mutate(groups1 = factor(groups1, levels = rev(n)), 
                     groups2 = factor(groups2, levels = rev(n))) %>%
    arrange(groups1)

In [32]:
color = setNames(n, c('#EEBEC0','#23B2E0','#BD9E64','#6483A4','#FAAE5F',
                      '#73ABCF','#000000','#EF2C2B','#27447C',
                      "#0072B2", "#E69F00", "#56B4E9", "#56B4E9", "#009E73", "#D55E00","#F0E442","#F0E442",
                "#CC79A7", "#787878", "#663300", "#663300", "#008080", "#008080"))
color

                                #EEBEC0                                 #23B2E0
   "Diencephalon glutamatergic neurons"        "Diencephalon GABAergic neurons"
                                #BD9E64                                 #6483A4
  "Mesencephalon glutamatergic neurons"       "Mesencephalon GABAergic neurons"
                                #FAAE5F                                 #73ABCF
"Rhombencephalon glutamatergic neurons"     "Rhombencephalon GABAergic neurons"
                                #000000                                 #EF2C2B
                             "Splatter"   "Telencephalon glutamatergic neurons"
                                #27447C                                 #0072B2
      "Telencephalon GABAergic neurons"                                    "18"
                                #E69F00                                 #56B4E9
                                   "11"                                    "10"
                                #56B4E9                                 #009E73
                                   "13"                                     "7"
                                #D55E00                                 #F0E442
                                   "15"                                     "0"
                                #F0E442                                 #CC79A7
                                    "1"                                    "14"
                                #787878                                 #663300
                                   "21"                                     "2"
                                #663300                                 #008080
                                   "17"                                    "16"
                                #008080
                                    "9"

In [33]:
mat$color <- names(color)[match(mat$groups1, color)]
mat$sp <- vapply(mat$source, FUN = function(x){
    strsplit(x, split = '_')[[1]][1]
}, FUN.VALUE = character(1))
mat$sp2 <- vapply(mat$target, FUN = function(x){
    strsplit(x, split = '_')[[1]][1]
}, FUN.VALUE = character(1))

In [34]:
# select linkages between amphioxus and vertebrates
mat <- mat %>% filter(sp == 'bf' | sp2 == 'bf')
# show only one direction
mat[mat$sp2 == 'bf', 'value'] = 0

In [35]:
# manually add gaps
test = vapply(unique(mat[[1]]), FUN = function(x){strsplit(x, split = '_')[[1]][1]},FUN.VALUE = character(1))
gaps = numeric(length(test))
for (i in 1:(length(gaps)-1)) {
  # Check if the current element is different from the previous one
  if (test[i] != test[i + 1]) {
    gaps[i] <- 1
  } else {
    gaps[i] <- 0
  }
}

In [36]:
circos.par(gap.after = gaps, track.margin = c(0, 0.01))
grid.col = setNames(mat$color, mat$source)
# highlight bf glia linkages
border_df = mat[grepl("bf", mat$source), 1:2]
border_df = rbind(border_df, mat[grepl("bf", mat$target), 1:2])
#border_df <- rbind(border_df, border_df2)
border_df$p = rep(x = 1, times = nrow(border_df))

In [37]:
pdf("vertebrate_neurons.chord_plot2.pdf", width = 20, height = 20)

species_colors <- c("hs" = "#989A9C", "mm" = "#F7D08D", "pv" = "#BF83A5", "pm" = "#8684B0", "bf" = '#702963')
chordDiagram(mat[,1:3], directional = 1, direction.type = c("arrows"), link.arr.type = "big.arrow", 
             grid.col = grid.col, link.visible = mat[[3]] > 0.2,
            annotationTrack = "grid", preAllocateTracks = list(track.height = 0.02))

circos.trackPlotRegion(
    track.index = 1,
  ylim = c(0, 1),  # Define the vertical range for the track
  track.height = 0.02,  # Adjust track height as needed
  bg.border = NA,  # No border for the track
  panel.fun = function(x, y) {
    sector.index <- CELL_META$sector.index  # Current sector
    species <- mat$sp[mat$source == sector.index]  # Match species to the current sector
    
    # Draw colored rectangles for each species
    circos.rect(
      xleft = CELL_META$cell.xlim[1], xright = CELL_META$cell.xlim[2], 
      ybottom = 0, ytop = 1, 
      col = species_colors[species], border = NA
    )
  }
)
circos.track(track.index = 2, panel.fun = function(x, y) {
    circos.text(CELL_META$xcenter, CELL_META$ylim[1], CELL_META$sector.index, 
        facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.05), cex = 1)
}, bg.border = NA) # here set bg.border to NA is important


dev.off()
circos.clear()

pdf
  2

In [16]:
# print some statistics

In [17]:
mat %>% filter(groups1 != groups2) %>% filter(sp =='pm' & groups2 %in% c('Oligodendrocytes', 'Oligodendrocyte precursor cells'))

   source              target       value     groups1
1  pm_Ast_254          hs_OPC_556   0.2990799 Astrocytes
2  pm_Epen_304         hs_OPC_556   0.2588697 Ependymal cells
3  pm_Erythrocytes_301 hs_Oligo_521 0.4456225 Erythrocytes
4  pm_Erythrocytes_301 hs_Oligo_529 0.5084667 Erythrocytes
5  pm_Erythrocytes_301 hs_Oligo_533 0.3069232 Erythrocytes
6  pm_Erythrocytes_301 hs_Oligo_550 0.2966744 Erythrocytes
7  pm_Erythrocytes_301 mm_Oligo_361 0.3543942 Erythrocytes
8  pm_Erythrocytes_301 mm_Oligo_364 0.2323280 Erythrocytes
9  pm_Erythrocytes_301 mm_Oligo_365 0.3377884 Erythrocytes
10 pm_Erythrocytes_301 mm_Oligo_366 0.5329679 Erythrocytes
11 pm_Erythrocytes_301 mm_Oligo_367 0.7176031 Erythrocytes
12 pm_Erythrocytes_301 mm_Oligo_370 0.3871790 Erythrocytes
13 pm_Erythrocytes_301 mm_Oligo_372 0.2160643 Erythrocytes
14 pm_Erythrocytes_301 mm_Oligo_375 0.5132782 Erythrocytes
15 pm_Erythrocytes_301 mm_Oligo_378 0.5544493 Erythrocytes
16 pm_Erythrocytes_301 mm_Oligo_380 0.3065038 Erythrocytes
17 pm_Erythrocytes_301 mm_Oligo_382 0.2809132 Erythrocytes
18 pm_Erythrocytes_301 mm_Oligo_384 0.2940163 Erythrocytes
19 pm_Fibro_15         hs_Oligo_529 0.3063509 Fibroblasts
20 pm_Fibro_15         hs_Oligo_542 0.2957713 Fibroblasts
21 pm_Fibro_23         hs_Oligo_529 0.2951858 Fibroblasts
22 pm_Fibro_26         hs_Oligo_529 0.2804183 Fibroblasts
23 pm_Fibro_26         hs_Oligo_542 0.2133596 Fibroblasts
24 pm_Fibro_30         hs_Oligo_542 0.2355461 Fibroblasts
25 pm_Fibro_58         hs_Oligo_542 0.3691130 Fibroblasts
26 pm_Fibro_59         hs_Oligo_542 0.5193487 Fibroblasts
27 pm_Fibro_60         hs_Oligo_529 0.2395893 Fibroblasts
28 pm_Fibro_61         hs_Oligo_529 0.2264089 Fibroblasts
29 pm_Fibro_62         hs_Oligo_529 0.3255821 Fibroblasts
30 pm_Fibro_63         hs_Oligo_529 0.2600408 Fibroblasts
31 pm_Fibro_73         hs_Oligo_529 0.2870352 Fibroblasts
32 pm_Fibro_76         hs_Oligo_529 0.2563186 Fibroblasts
33 pm_Fibro_78         hs_Oligo_529 0.2577079 Fibroblasts
34 pm_Fibro_78         hs_Oligo_542 0.2037827 Fibroblasts
35 pm_Fibro_80         hs_Oligo_529 0.2486954 Fibroblasts
36 pm_Fibro_81         hs_Oligo_529 0.2122717 Fibroblasts
37 pm_Fibro_82         hs_Oligo_529 0.2054154 Fibroblasts
38 pm_Fibro_83         hs_Oligo_529 0.2299773 Fibroblasts
39 pm_Fibro_87         hs_Oligo_529 0.2143719 Fibroblasts
40 pm_Fibro_90         hs_Oligo_529 0.2250938 Fibroblasts
41 pm_Fibro_91         hs_Oligo_529 0.2398631 Fibroblasts
42 pm_Microglia_297    mm_Oligo_388 0.3059680 Microglia
43 pm_Microglia_297    mm_Oligo_389 0.2655446 Microglia
   groups2                         color   sp
1  Oligodendrocyte precursor cells #8BCF02 pm
2  Oligodendrocyte precursor cells #B4DEA2 pm
3  Oligodendrocytes                #EF2C2B pm
4  Oligodendrocytes                #EF2C2B pm
5  Oligodendrocytes                #EF2C2B pm
6  Oligodendrocytes                #EF2C2B pm
7  Oligodendrocytes                #EF2C2B pm
8  Oligodendrocytes                #EF2C2B pm
9  Oligodendrocytes                #EF2C2B pm
10 Oligodendrocytes                #EF2C2B pm
11 Oligodendrocytes                #EF2C2B pm
12 Oligodendrocytes                #EF2C2B pm
13 Oligodendrocytes                #EF2C2B pm
14 Oligodendrocytes                #EF2C2B pm
15 Oligodendrocytes                #EF2C2B pm
16 Oligodendrocytes                #EF2C2B pm
17 Oligodendrocytes                #EF2C2B pm
18 Oligodendrocytes                #EF2C2B pm
19 Oligodendrocytes                #6B6B6B pm
20 Oligodendrocytes                #6B6B6B pm
21 Oligodendrocytes                #6B6B6B pm
22 Oligodendrocytes                #6B6B6B pm
23 Oligodendrocytes                #6B6B6B pm
24 Oligodendrocytes                #6B6B6B pm
25 Oligodendrocytes                #6B6B6B pm
26 Oligodendrocytes                #6B6B6B pm
27 Oligodendrocytes                #6B6B6B pm
28 Oligodendrocytes                #6B6B6B pm
29 Oligodendrocytes                #6B6B6B pm
30 Oligodendrocytes                #6B6B6B pm
31 Oligodendrocytes                #6B6B6B pm
32 Oligodendrocytes                #6B6B6B pm
33 Oligodendrocytes                #6B6B6B pm
34 Oligodendrocytes                #6B6B6B pm
35 Oligodendrocytes                #6B6B6B pm
36 Oligodendrocytes                #6B6B6B pm
37 Oligodendrocytes                #6B6B6B pm
38 Oligodendrocytes                #6B6B6B pm
39 Oligodendrocytes                #6B6B6B pm
40 Oligodendrocytes                #6B6B6B pm
41 Oligodendrocytes                #6B6B6B pm
42 Oligodendrocytes                #3B549D pm
43 Oligodendrocytes                #3B549D pm

In [18]:
dim(mat)

[1] 1022    7

In [19]:
tmp <- mat %>% filter(groups1 != groups2) %>% 
    filter(!(groups1 == 'Astrocytes' & groups2 == 'Ependymal cells')) %>%
    filter(!(groups2 == 'Astrocytes' & groups1 == 'Ependymal cells')) %>% 
    #filter(!(groups1 == 'Fibroblasts' & groups2 == 'Vascular cells')) %>%
    #filter(!(groups2 == 'Fibroblasts' & groups1 == 'Vascular cells')) %>% 
    filter(!(groups1 == 'Oligodendrocytes' & groups2 == 'Oligodendrocyte precursor cells')) %>%
    filter(!(groups1 == 'Oligodendrocyte precursor cells' & groups2 == 'Oligodendrocytes')) 
# bidirectional linkages
tmp[c("source", "target")] <- t(apply(tmp[c("source", "target")], 1, sort))
tmp <- tmp[!duplicated(tmp[c("source", "target")]), ]
tmp

   source       target              value     groups1
1  hs_OPC_556   pm_Ast_254          0.2990799 Astrocytes
2  hs_OPC_556   pm_Epen_304         0.2588697 Ependymal cells
3  hs_Oligo_521 pm_Erythrocytes_301 0.4456225 Erythrocytes
4  hs_Oligo_529 pm_Erythrocytes_301 0.5084667 Erythrocytes
5  hs_Oligo_533 pm_Erythrocytes_301 0.3069232 Erythrocytes
6  hs_Oligo_550 pm_Erythrocytes_301 0.2966744 Erythrocytes
7  mm_Oligo_361 pm_Erythrocytes_301 0.3543942 Erythrocytes
8  mm_Oligo_364 pm_Erythrocytes_301 0.2323280 Erythrocytes
9  mm_Oligo_365 pm_Erythrocytes_301 0.3377884 Erythrocytes
10 mm_Oligo_366 pm_Erythrocytes_301 0.5329679 Erythrocytes
11 mm_Oligo_367 pm_Erythrocytes_301 0.7176031 Erythrocytes
12 mm_Oligo_370 pm_Erythrocytes_301 0.3871790 Erythrocytes
13 mm_Oligo_372 pm_Erythrocytes_301 0.2160643 Erythrocytes
14 mm_Oligo_375 pm_Erythrocytes_301 0.5132782 Erythrocytes
15 mm_Oligo_378 pm_Erythrocytes_301 0.5544493 Erythrocytes
16 mm_Oligo_380 pm_Erythrocytes_301 0.3065038 Erythrocytes
17 mm_Oligo_382 pm_Erythrocytes_301 0.2809132 Erythrocytes
18 mm_Oligo_384 pm_Erythrocytes_301 0.2940163 Erythrocytes
19 hs_Oligo_529 pm_Fibro_15         0.3063509 Fibroblasts
20 hs_Oligo_542 pm_Fibro_15         0.2957713 Fibroblasts
21 hs_Oligo_529 pm_Fibro_23         0.2951858 Fibroblasts
22 hs_Oligo_529 pm_Fibro_26         0.2804183 Fibroblasts
23 hs_Oligo_542 pm_Fibro_26         0.2133596 Fibroblasts
24 hs_Oligo_542 pm_Fibro_30         0.2355461 Fibroblasts
25 hs_Oligo_542 pm_Fibro_58         0.3691130 Fibroblasts
26 hs_Oligo_542 pm_Fibro_59         0.5193487 Fibroblasts
27 hs_Oligo_529 pm_Fibro_60         0.2395893 Fibroblasts
28 hs_Oligo_529 pm_Fibro_61         0.2264089 Fibroblasts
29 hs_Oligo_529 pm_Fibro_62         0.3255821 Fibroblasts
30 hs_Oligo_529 pm_Fibro_63         0.2600408 Fibroblasts
⋮  ⋮            ⋮                   ⋮         ⋮
61 mm_Vasc_461  pm_Fibro_64         0.2391309 Fibroblasts
62 pm_Fibro_64  pv_Vasc_549         0.6818436 Fibroblasts
63 mm_Vasc_460  pm_Fibro_66         0.2254614 Fibroblasts
64 mm_Vasc_461  pm_Fibro_66         0.2201097 Fibroblasts
65 pm_Fibro_66  pv_Vasc_549         0.3679650 Fibroblasts
66 mm_Vasc_460  pm_Fibro_67         0.3360076 Fibroblasts
67 mm_Vasc_461  pm_Fibro_67         0.2972089 Fibroblasts
68 pm_Fibro_67  pv_Vasc_549         0.6037641 Fibroblasts
69 pm_Fibro_70  pv_Vasc_549         0.3837312 Fibroblasts
70 mm_Vasc_460  pm_Fibro_73         0.2223323 Fibroblasts
71 pm_Fibro_73  pv_Vasc_549         0.2600951 Fibroblasts
72 pm_Fibro_76  pv_Vasc_549         0.2045855 Fibroblasts
73 mm_Vasc_460  pm_Fibro_78         0.2060224 Fibroblasts
74 pm_Fibro_78  pv_Vasc_549         0.3735456 Fibroblasts
75 mm_Vasc_460  pm_Fibro_80         0.3873016 Fibroblasts
76 mm_Vasc_461  pm_Fibro_80         0.2775264 Fibroblasts
77 pm_Fibro_80  pv_Vasc_549         0.5662673 Fibroblasts
78 pm_Fibro_81  pv_Vasc_549         0.2423956 Fibroblasts
79 pm_Fibro_82  pv_Vasc_549         0.2022029 Fibroblasts
80 pm_Fibro_85  pv_Vasc_549         0.2255663 Fibroblasts
81 mm_Vasc_460  pm_Fibro_87         0.2344829 Fibroblasts
82 pm_Fibro_87  pv_Vasc_549         0.2987918 Fibroblasts
83 mm_Vasc_460  pm_Fibro_89         0.3101841 Fibroblasts
84 pm_Fibro_89  pv_Vasc_549         0.4666154 Fibroblasts
85 mm_Vasc_460  pm_Fibro_90         0.2194843 Fibroblasts
86 pm_Fibro_90  pv_Vasc_549         0.3952765 Fibroblasts
87 pm_Fibro_91  pv_Vasc_549         0.3230698 Fibroblasts
88 hs_Oligo_521 pv_Microglia_273    0.2556674 Microglia
89 mm_Oligo_388 pm_Microglia_297    0.3059680 Microglia
90 mm_Oligo_389 pm_Microglia_297    0.2655446 Microglia
   groups2                         color   sp
1  Oligodendrocyte precursor cells #8BCF02 pm
2  Oligodendrocyte precursor cells #B4DEA2 pm
3  Oligodendrocytes                #EF2C2B pm
4  Oligodendrocytes                #EF2C2B pm
5  Oligodendrocytes                #EF2C2B pm
6  Oligodendrocytes                #EF2C2B pm
7  Oligodendrocytes                #EF2C2B pm
8  Oligodendrocytes                #EF2C2B pm
9  Oligodendrocytes                #EF2C2B pm
10 Oligodendrocytes                #EF2C2B pm
11 Oligodendrocytes                #EF2C2B pm
12 Oligodendrocytes                #EF2C2B pm
13 Oligodendrocytes                #EF2C2B pm
14 Oligodendrocytes                #EF2C2B pm
15 Oligodendrocytes                #EF2C2B pm
16 Oligodendrocytes                #EF2C2B pm
17 Oligodendrocytes                #EF2C2B pm
18 Oligodendrocytes                #EF2C2B pm
19 Oligodendrocytes                #6B6B6B pm
20 Oligodendrocytes                #6B6B6B pm
21 Oligodendrocytes                #6B6B6B pm
22 Oligodendrocytes                #6B6B6B pm
23 Oligodendrocytes                #6B6B6B pm
24 Oligodendrocytes                #6B6B6B pm
25 Oligodendrocytes                #6B6B6B pm
26 Oligodendrocytes                #6B6B6B pm
27 Oligodendrocytes                #6B6B6B pm
28 Oligodendrocytes                #6B6B6B pm
29 Oligodendrocytes                #6B6B6B pm
30 Oligodendrocytes                #6B6B6B pm
⋮  ⋮                               ⋮       ⋮
61 Vascular cells                  #6B6B6B pm
62 Vascular cells                  #6B6B6B pm
63 Vascular cells                  #6B6B6B pm
64 Vascular cells                  #6B6B6B pm
65 Vascular cells                  #6B6B6B pm
66 Vascular cells                  #6B6B6B pm
67 Vascular cells                  #6B6B6B pm
68 Vascular cells                  #6B6B6B pm
69 Vascular cells                  #6B6B6B pm
70 Vascular cells                  #6B6B6B pm
71 Vascular cells                  #6B6B6B pm
72 Vascular cells                  #6B6B6B pm
73 Vascular cells                  #6B6B6B pm
74 Vascular cells                  #6B6B6B pm
75 Vascular cells                  #6B6B6B pm
76 Vascular cells                  #6B6B6B pm
77 Vascular cells                  #6B6B6B pm
78 Vascular cells                  #6B6B6B pm
79 Vascular cells                  #6B6B6B pm
80 Vascular cells                  #6B6B6B pm
81 Vascular cells                  #6B6B6B pm
82 Vascular cells                  #6B6B6B pm
83 Vascular cells                  #6B6B6B pm
84 Vascular cells                  #6B6B6B pm
85 Vascular cells                  #6B6B6B pm
86 Vascular cells                  #6B6B6B pm
87 Vascular cells                  #6B6B6B pm
88 Oligodendrocytes                #3B549D pv
89 Oligodendrocytes                #3B549D pm
90 Oligodendrocytes                #3B549D pm

In [20]:
mat %>% group_by(groups1) %>% count(sp, sort = TRUE) %>% arrange(groups1)

   groups1                         sp n
1  Astrocytes                      pv 90
2  Astrocytes                      hs 81
3  Astrocytes                      mm 77
4  Astrocytes                      pm 52
5  Choroid plexus epithelial cells hs  6
6  Choroid plexus epithelial cells mm  6
7  Choroid plexus epithelial cells pm  6
8  Choroid plexus epithelial cells pv  2
9  Ependymal cells                 pm 31
10 Ependymal cells                 mm 16
11 Ependymal cells                 pv  9
12 Ependymal cells                 hs  8
13 Erythrocytes                    pm 16
14 Fibroblasts                     pm 60
15 Fibroblasts                     hs 11
16 Microglia                       pm 38
17 Microglia                       pv 37
18 Microglia                       hs 31
19 Microglia                       mm 23
20 Oligodendrocyte precursor cells hs 21
21 Oligodendrocyte precursor cells pv 10
22 Oligodendrocyte precursor cells mm  9
23 Oligodendrocytes                mm 86
24 Oligodendrocytes                hs 81
25 Oligodendrocytes                pv 77
26 Vascular cells                  mm 57
27 Vascular cells                  pv 42
28 Vascular cells                  pm 21
29 Vascular cells                  hs 18

In [22]:
mat[c("source", "target")] <- t(apply(mat[c("source", "target")], 1, sort))
mat <- mat[!duplicated(mat[c("source", "target")]), ]
mat

     source      target      value     groups1        groups2        color   sp
1    hs_Ast_593  mm_Ast_495  0.3765032 Astrocytes     Astrocytes     #8BCF02 hs
2    hs_Ast_593  mm_Ast_504  0.5169962 Astrocytes     Astrocytes     #8BCF02 hs
3    hs_Ast_593  mm_Ast_505  0.3592002 Astrocytes     Astrocytes     #8BCF02 hs
4    hs_Ast_593  mm_Ast_506  0.6811880 Astrocytes     Astrocytes     #8BCF02 hs
5    hs_Ast_593  mm_Ast_507  0.7968926 Astrocytes     Astrocytes     #8BCF02 hs
6    hs_Ast_593  mm_Ast_509  0.7639273 Astrocytes     Astrocytes     #8BCF02 hs
7    hs_Ast_593  pv_Ast_315  0.2301026 Astrocytes     Astrocytes     #8BCF02 hs
8    hs_Ast_593  pv_Ast_319  0.2218708 Astrocytes     Astrocytes     #8BCF02 hs
9    hs_Ast_593  pv_Ast_321  0.2078996 Astrocytes     Astrocytes     #8BCF02 hs
10   hs_Ast_593  pv_Ast_322  0.2677238 Astrocytes     Astrocytes     #8BCF02 hs
11   hs_Ast_593  pv_Ast_323  0.2820405 Astrocytes     Astrocytes     #8BCF02 hs
12   hs_Ast_593  pv_Ast_324  0.2724215 Astrocytes     Astrocytes     #8BCF02 hs
13   hs_Ast_593  pv_Ast_327  0.2680215 Astrocytes     Astrocytes     #8BCF02 hs
14   hs_Ast_593  pv_Ast_337  0.5535952 Astrocytes     Astrocytes     #8BCF02 hs
15   hs_Ast_593  pv_Ast_352  0.3439520 Astrocytes     Astrocytes     #8BCF02 hs
16   hs_Ast_593  pv_Ast_354  0.4185428 Astrocytes     Astrocytes     #8BCF02 hs
17   hs_Ast_593  pv_Ast_577  0.3025332 Astrocytes     Astrocytes     #8BCF02 hs
18   hs_Ast_593  pm_Ast_238  0.2791621 Astrocytes     Astrocytes     #8BCF02 hs
19   hs_Ast_593  pm_Ast_240  0.5186498 Astrocytes     Astrocytes     #8BCF02 hs
20   hs_Ast_593  pm_Ast_252  0.2788566 Astrocytes     Astrocytes     #8BCF02 hs
21   hs_Ast_593  pm_Ast_253  0.4654658 Astrocytes     Astrocytes     #8BCF02 hs
22   hs_Ast_593  pm_Ast_254  0.3683224 Astrocytes     Astrocytes     #8BCF02 hs
23   hs_Ast_593  pm_Ast_256  0.4035593 Astrocytes     Astrocytes     #8BCF02 hs
24   hs_Ast_593  pm_Ast_258  0.3368137 Astrocytes     Astrocytes     #8BCF02 hs
25   hs_Ast_593  pm_Ast_259  0.4514637 Astrocytes     Astrocytes     #8BCF02 hs
26   hs_Ast_593  pm_Ast_261  0.4110279 Astrocytes     Astrocytes     #8BCF02 hs
27   hs_Ast_593  pm_Ast_263  0.3319698 Astrocytes     Astrocytes     #8BCF02 hs
28   hs_Ast_606  mm_Ast_498  0.7030602 Astrocytes     Astrocytes     #8BCF02 hs
29   hs_Ast_606  pv_Ast_354  0.4708090 Astrocytes     Astrocytes     #8BCF02 hs
30   hs_Ast_609  mm_Ast_498  0.8453866 Astrocytes     Astrocytes     #8BCF02 hs
⋮    ⋮           ⋮           ⋮         ⋮              ⋮              ⋮       ⋮
947  hs_Vasc_584 mm_Vasc_456 0.6876846 Vascular cells Vascular cells #E7E6D4 hs
948  hs_Vasc_584 pv_Vasc_556 0.7423802 Vascular cells Vascular cells #E7E6D4 hs
950  mm_Vasc_412 pv_Vasc_555 0.6108306 Vascular cells Vascular cells #E7E6D4 mm
951  mm_Vasc_412 pm_Vasc_5   0.3180588 Vascular cells Vascular cells #E7E6D4 mm
953  mm_Vasc_417 pv_Vasc_555 0.8951153 Vascular cells Vascular cells #E7E6D4 mm
954  mm_Vasc_417 pm_Vasc_5   0.2632823 Vascular cells Vascular cells #E7E6D4 mm
956  mm_Vasc_419 pv_Vasc_555 0.5901845 Vascular cells Vascular cells #E7E6D4 mm
957  mm_Vasc_419 pm_Vasc_5   0.3666024 Vascular cells Vascular cells #E7E6D4 mm
959  mm_Vasc_421 pv_Vasc_555 0.5805820 Vascular cells Vascular cells #E7E6D4 mm
961  mm_Vasc_424 pv_Vasc_555 0.4640019 Vascular cells Vascular cells #E7E6D4 mm
963  mm_Vasc_426 pv_Vasc_555 0.8550427 Vascular cells Vascular cells #E7E6D4 mm
964  mm_Vasc_426 pm_Vasc_2   0.4194695 Vascular cells Vascular cells #E7E6D4 mm
965  mm_Vasc_426 pm_Vasc_3   0.7459753 Vascular cells Vascular cells #E7E6D4 mm
966  mm_Vasc_426 pm_Vasc_4   0.8041047 Vascular cells Vascular cells #E7E6D4 mm
967  mm_Vasc_426 pm_Vasc_5   0.8489065 Vascular cells Vascular cells #E7E6D4 mm
968  mm_Vasc_426 pm_Vasc_6   0.8481896 Vascular cells Vascular cells #E7E6D4 mm
971  mm_Vasc_452 pv_Vasc_556 0.8647708 Vascular cells Vascular cells #E7E6D4 mm
972  mm_Vasc_452 pm_Vasc_37  0.6921416 Vascular cells Vascular cells #E7E6D4 mm
975  mm_Vasc_456 pv_Vasc_556 0.7766593 Vascular cells Vascular cells #E7E6D4 mm
976  mm_Vasc_456 pm_Vasc_37  0.7567390 Vascular cells Vascular cells #E7E6D4 mm
977  mm_Vasc_458 pv_Vasc_549 0.5504955 Vascular cells Vascular cells #E7E6D4 mm
978  mm_Vasc_459 pv_Vasc_549 0.6120812 Vascular cells Vascular cells #E7E6D4 mm
979  mm_Vasc_460 pv_Vasc_549 0.8117831 Vascular cells Vascular cells #E7E6D4 mm
980  mm_Vasc_461 pv_Vasc_549 0.8346801 Vascular cells Vascular cells #E7E6D4 mm
992  pm_Vasc_2   pv_Vasc_555 0.6830054 Vascular cells Vascular cells #E7E6D4 pv
993  pm_Vasc_3   pv_Vasc_555 0.7839701 Vascular cells Vascular cells #E7E6D4 pv
994  pm_Vasc_4   pv_Vasc_555 0.7209644 Vascular cells Vascular cells #E7E6D4 pv
995  pm_Vasc_5   pv_Vasc_555 0.8103662 Vascular cells Vascular cells #E7E6D4 pv
996  pm_Vasc_6   pv_Vasc_555 0.7411247 Vascular cells Vascular cells #E7E6D4 pv
1001 pm_Vasc_37  pv_Vasc_556 0.7708705 Vascular cells Vascular cells #E7E6D4 pv

In [23]:
# ratio of mapping with the same families
(511-44)/511

[1] 0.9138943

In [20]:
?chordDiagram